const logIn=require('../helpers/logIn')
const transactions = require('../pageobjects/transactionObject')
const cashTransfer=require('../pageobjects/cashTransferObjects')
const BulkEntries = require('../pageobjects/bulkEntriesObjects')


describe('Financfy Bulk Entries Page Test', () => {
  it('Bulk Entries transactions', async () => {
    await logIn()

    //Navigate to Bulk Entries Tab
    await transactions.transactionMenu.click()
    await BulkEntries.bulkEntriesTab.click()

    //Create Bulk Entries(1st row)
    await BulkEntries.amountField1.setValue(112.45)
    await BulkEntries.typeField1.click()
    await BulkEntries.typeField1.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.typeOptionsForCashIn.click()
    await BulkEntries.contactField1.click()
    await BulkEntries.contactField1.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.contactOptions.click()
    await BulkEntries.categoryField1.click()
    await BulkEntries.categoryField1.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.categoryOptions.click()
    await BulkEntries.paymentMode1.click()
    await BulkEntries.paymentMode1.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.paymentModeOptions.click()
    //2nd row
    await BulkEntries.amountField2.setValue(500)
    await BulkEntries.typeField2.click()
    await BulkEntries.typeField2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.typeOptionsForCashOut.click()
    await BulkEntries.contactField2.click()
    await BulkEntries.contactField2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.contactOptions.click()
    await BulkEntries.categoryField2.click()
    await BulkEntries.categoryField2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.categoryOptions.click()
    await BulkEntries.paymentMode2.click()
    await BulkEntries.paymentMode2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.paymentModeOptions.click()
    //3rd row
    await BulkEntries.amountField3.setValue(300)
    await BulkEntries.typeField3.click()
    await BulkEntries.typeField3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.typeOptionsForCashIn.click()
    await BulkEntries.contactField3.click()
    await BulkEntries.contactField3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.contactOptions.click()
    await BulkEntries.categoryField3.click()
    await BulkEntries.categoryField3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.categoryOptions.click()
    await BulkEntries.paymentMode3.click()
    await BulkEntries.paymentMode3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.paymentModeOptions.click()
    await BulkEntries.saveAndNewText.click()
    await browser.pause(5000)
    await expect(cashTransfer.toastMsg).toBeDisplayed(
      'Successfully added transactions entries'
    )
  })
})
