const logIn = require('../pageobjects/logInObject')
const transactions = require('../pageobjects/transactionObject')
const BulkEntries = require('../pageobjects/bulkEntriesObjects')
require('dotenv').config()

describe('Financfy Bulk Entries Page Test', () => {
  it('Bulk Entries transactions', async () => {
    await browser.url(logIn.stagingURL)

    // Login steps
    await logIn.mobileNumber.setValue(process.env.MOBILE_NUMBER)
    await logIn.password.setValue(process.env.PASSWORD)
    await logIn.signinButton.click()
    //1st row
    await transactions.transactionMenu.click()
    await BulkEntries.bulkEntriesTab.click()
    await BulkEntries.amountField1.setValue(112.45)
    await BulkEntries.typeField.click()
    await BulkEntries.typeField.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.typeOptionsForCashIn.click()
    await BulkEntries.contactField.click()
    await BulkEntries.contactField.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.contactOptions.click()
    await BulkEntries.categoryField.click()
    await BulkEntries.categoryField.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.categoryOptions.click()
    await BulkEntries.paymentMode.click()
    await BulkEntries.paymentMode.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.paymentModeOptions.click()
    //2nd row
    await BulkEntries.amountField2.setValue(500)
    await BulkEntries.typeField2.click()
    await BulkEntries.typeField2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.typeOptionsForCashOut.click()
    await BulkEntries.contactField2.click()
    await BulkEntries.contactField2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.contactOptions.click()
    await BulkEntries.categoryField2.click()
    await BulkEntries.categoryField2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.categoryOptions.click()
    await BulkEntries.paymentMode2.click()
    await BulkEntries.paymentMode2.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.paymentModeOptions.click()
    //3rd row
    await BulkEntries.amountField3.setValue(300)
    await BulkEntries.typeField3.click()
    await BulkEntries.typeField3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.typeOptionsForCashIn.click()
    await BulkEntries.contactField3.click()
    await BulkEntries.contactField3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.contactOptions.click()
    await BulkEntries.categoryField3.click()
    await BulkEntries.categoryField3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.categoryOptions.click()
    await BulkEntries.paymentMode3.click()
    await BulkEntries.paymentMode3.waitForDisplayed({ timeout: 5000 })
    await BulkEntries.paymentModeOptions.click()
    await BulkEntries.saveAndNewText.click()
    await browser.pause(5000)
  })
})
